name: The Wandering Coder
markdown: redcarpet
github: https://www.github.com/smiller
about: Software developer, avid reader, occasional writer, and sometime mediaevalist.
excerpt_separator: ""
urls:
    - text: github
      url: https://github.com/smiller
    - text: weird cultural sean stuff
      url: http://weird-cultural-sean-stuff.ca
    - text: twitter
      url: https://twitter.com/seanmiller_ca
    - text: email
      url: mailto:sean@seanmiller.ca
